### ISSUE TITLE
Task1 - Stock News Scraping

### ISSUE THREAD

**Issue by Shashank1985** [opencodeiiita/News_Scraping#1]
This task is claim only
This task requires a higher order knowledge of python and web scraping
please upload your colab file link in read view to [TASK1_Solutions](https://github.com/opencodeiiita/News_Scraping/tree/main/TASK1_Solutions) creating txt file with name as your Enrollment/roll number. Link should be in read mode and access to
[iit2022008@iiita.ac.in](mailto:iit2022008@iiita.ac.in) & [22f3002029@ds.study.iitm.ac.in](mailto:22f3002029@ds.study.iitm.ac.in). (Don't make file public).

Please read the instructions.txt file carefully to understand what the objective of this task is
Please refer to resources.txt and other sources

**Comment by TheDivineAurora** [comment]
claim im interested

**Comment by Shashank1985** [comment]
accept the invite

**Comment by sarthakvermaa** [comment]
claim

**Comment by prakhar-py** [comment]
Claim

**Comment by ajay484** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by rnavaneeth992** [comment]
@Shashank1985  is it open for all? this task

**Comment by Shashank1985** [comment]
@rnavaneeth992 no, the task has been assigned

**Comment by rnavaneeth992** [comment]
ok

**Comment by Shashank1985** [comment]
@sarthakvermaa you are assigned this task

**Comment by coderatiiita** [comment]
claim

**Comment by Apoorv012** [comment]
claim
