### ISSUE TITLE
Task2-Financial News Scraping

### ISSUE THREAD

**Issue by Shashank1985** [opencodeiiita/News_Scraping#2]
Pretty basic intro to web scraping for beginners
Task 2 is independent of task 1
please upload your colab file link in read view to *[TASK2_Solutions](https://github.com/opencodeiiita/News_Scraping/tree/main/TASK2_Solutions)* creating txt file with name as your Enrollment/roll number. Link should be in read mode and access to
[iit2022008@iiita.ac.in](mailto:iit2022008@iiita.ac.in). (Don't make file public).

for resources refer to resources.txt file

**Comment by Nandinig24** [comment]
what exactly we have to do please explain more clearly
