### ISSUE TITLE
Sentiment Analysis

### ISSUE THREAD

**Issue by breakthe-rule** [opencodeiiita/News_Scraping#30]
> This Is FCFS Issue.

**Till Now We Have Scrapped News Headlines. But You Know What More Important Is?? It Is Getting Sentiment of These Headlines: <ins>Positive</ins>, <ins>Negative </ins>or <ins>Neutral</ins> !! One Of The Important Use-Case Of Sentiment Analysis On Headlines Is Predicting Market Condition, More Specifically Condition Of Particular Company In Market.**

## Task:
Use this [Pre-trained Model](https://huggingface.co/mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis) To Find Sentiment Of Headlines You Have Scraped Till Now.

* If Possible Try To Optimize Your Code Such That It Utilizes Least Memory

## Output Format:
* Create A Folder Of Your Roll Number.
* Insert <ins>Code</ins> and <ins>.xlsx file</ins> (With Only 4️ Columns: Headline and Probability Of Each Sentiment)

⚠️ You Only Have 1 Day For This Issue

**Comment by Apoorv012** [comment]
claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by breakthe-rule** [comment]
@Apoorv012 had you contributed in task2 ?

**Comment by DikshantK2004** [comment]
Claim

**Comment by Apoorv012** [comment]
@breakthe-rule I thought this was independent of that
